--- 
components: 
  schemas: 
    VehicleModel: 
      $ref: "https://smart-data-models.github.io/dataModel.Transportation/VehicleModel/schema.yaml#/VehicleModel"
info: 
  description: >-
        This entity models a particular vehicle model, including all properties
        which are common to multiple vehicle instances belonging to such model.
  title: VehicleModel
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
    
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - VehicleModel
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Transportation/VehicleModel/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Transportation/VehicleModel/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
