RoadSegment:
  required:
    - id
    - name
    - type
    - refRoad
    - startPoint
    - endPoint
    - allowedVehicleType
    - totalLaneNumber
    - laneUsage
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: >-
    This entity contains a harmonised geographic and contextual description of a
    road segment. A collection of road segments are used to describe a Road.
    Road segments can include several lanes. This data model allows to convey
    road segments made up of heterogeneous lanes (different in their usage,
    speed, height, etc.). Lanes are identified by using integer numbers between
    1 and n, being number 1 the lane to the right when going forwards. The
    forward direction is the direction denoted by the vector which goes from the
    segment"s start point to the segment"s end point. This is the same
    convention as the one used by OpenStreetMap. This entity is primarily
    associated with the Automotive and Smart City vertical segments and related
    IoT applications. This data model has been developed in cooperation with
    mobile operators and the GSMA.
  properties:
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    allowedVehicleType:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - agriculturalVehicle
          - bicycle
          - bus
          - car
          - caravan
          - carWithCaravan
          - carWithTrailer
          - constructionOrMaintenanceVehicle
          - lorry
          - moped
          - motorcycle
          - motorcycleWithSideCar
          - motorscooter
          - tanker
          - trailer
          - van
          - anyVehicle
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    annotations:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    category:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    color:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    endKilometer:
      x-ngsi:
        type: Property
      type: number
      description: ''
    image:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    laneUsage:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - forward
          - backward
    length:
      x-ngsi:
        type: Property
      type: number
      description: ''
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    maximumAllowedHeight:
      x-ngsi:
        type: Property
      type: number
      description: ''
    maximumAllowedSpeed:
      x-ngsi:
        type: Property
      type: number
      description: ''
    maximumAllowedWeight:
      x-ngsi:
        type: Property
      type: number
      description: ''
    minimumAllowedSpeed:
      x-ngsi:
        type: Property
      type: number
      description: ''
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    startKilometer:
      x-ngsi:
        type: Property
      type: number
      description: ''
    totalLaneNumber:
      x-ngsi:
        type: Property
      type: number
      description: ''
    width:
      x-ngsi:
        type: Property
      type: number
      description: ''
