Vehicle:
  required:
    - id
    - type
    - vehicleType
    - category
    - location
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: >-
    This entity models a particular vehicle model, including all properties
    which are common to multiple vehicle instances belonging to such model.
  properties:
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    annotations:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    cargoWeight:
      x-ngsi:
        type: Property
      type: number
      description: ''
    category:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - public
          - private
          - municipalServices
          - specialUsage
          - tracked
          - nonTracked
    color:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dateFirstUsed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
      format: date
    dateVehicleFirstRegistered:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
      format: date
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    feature:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - gps
          - airbag
          - overspeed
          - abs
          - wifi
          - backCamera
          - proximitySensor
          - disabledRamp
          - alarm
          - internetConnection
    fleetVehicleId:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    image:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    mileageFromOdometer:
      x-ngsi:
        type: Property
      type: number
      description: ''
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    purchaseDate:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    serviceProvided:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - garbageCollection
          - parksAndGardens
          - construction
          - streetLighting
          - roadSignalling
          - cargoTransport
          - urbanTransit
          - maintenance
          - streetCleaning
          - wasteContainerCleaning
          - auxiliaryServices
          - goodsSelling
          - fairground
          - specialTransport
    serviceStatus:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    vehicleConfiguration:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    vehicleIdentificationNumber:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    vehiclePlateIdentifier:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    vehicleSpecialUsage:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    vehicleType:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
